export const RESET = {
  fileFormat: "",
  fileName: "",
  audioPath: "",
  audioFormat: "",
  audioNamePattern: "",
  audioPrefix: "",
  audioSuffix: "",
  transcriptionPath: "",
  transcriptionName: "",
  transcriptionFormat: "",
  includePath: false,
  transcriptionDelimiter: "",
  // sampleRate: 22050,
  // sampleSize: 16,
  // channels: "",
};

export const LJSPEECH = {
  fileFormat: "zip",
  fileName: "ljspeech",
  audioPath: "wavs",
  audioFormat: "wav",
  audioNamePattern: "zeros",
  audioPrefix: "LJ001-",
  audioSuffix: "",
  transcriptionPath: "",
  transcriptionName: "transcripts",
  transcriptionFormat: "csv",
  includePath: false,
  transcriptionDelimiter: "|",
  sampleRate: 22050,
  sampleSize: 16,
  channels: 1,
};

export const PIPER_MEDHIGH = {
  fileFormat: "zip",
  fileName: "piper",
  audioPath: "wavs",
  audioFormat: "wav",
  audioNamePattern: "asc",
  audioPrefix: "",
  audioSuffix: "",
  transcriptionPath: "",
  transcriptionName: "metadata",
  transcriptionFormat: "csv",
  includePath: false,
  transcriptionDelimiter: "|",
  sampleRate: 22050,
  sampleSize: 16,
  channels: 1,
};

export const PIPER_LOW = {
  fileFormat: "zip",
  fileName: "piper",
  audioPath: "wavs",
  audioFormat: "wav",
  audioNamePattern: "asc",
  audioPrefix: "",
  audioSuffix: "",
  transcriptionPath: "",
  transcriptionName: "metadata",
  transcriptionFormat: "csv",
  includePath: false,
  transcriptionDelimiter: "|",
  sampleRate: 16000,
  sampleSize: 16,
  channels: 1,
};

export const AUDIO_FORMATS = ["wav", "mp3", "webm"];
